#!/usr/bin/env node
/**
 * 讀 output/*.json,把每篇 story 的 sentences 餵給 VOICEVOX,
 * mp3 寫進 audio/tts/,manifest.js 同步更新。
 *
 * 用法:
 *   node scripts/daily-stories/tts.mjs                 # 全部
 *   node scripts/daily-stories/tts.mjs --level n5      # 只 N5
 */

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';

const ROOT = path.resolve(import.meta.dirname, '../..');
const OUT_DIR = path.join(ROOT, 'audio/tts');
const STORIES_DIR = path.join(import.meta.dirname, 'output');
const MANIFEST = path.join(OUT_DIR, 'manifest.js');
const ENGINE = 'http://127.0.0.1:50021';
const SPEAKER = 2; // 四国めたん ノーマル

const argv = process.argv.slice(2);
function arg(name) { const i = argv.indexOf('--' + name); return i >= 0 ? argv[i + 1] : null; }
const filterLevel = arg('level');

function hashText(t) { return crypto.createHash('sha1').update(t).digest('hex').slice(0, 12); }

async function audioQuery(text) {
  const r = await fetch(`${ENGINE}/audio_query?speaker=${SPEAKER}&text=${encodeURIComponent(text)}`, { method: 'POST' });
  if (!r.ok) throw new Error('audio_query ' + r.status);
  return r.json();
}
async function synthesis(query) {
  const r = await fetch(`${ENGINE}/synthesis?speaker=${SPEAKER}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(query),
  });
  if (!r.ok) throw new Error('synthesis ' + r.status);
  return Buffer.from(await r.arrayBuffer());
}
function wavToMp3(wavBuf, outPath) {
  const tmpWav = outPath + '.tmp.wav';
  fs.writeFileSync(tmpWav, wavBuf);
  spawnSync('ffmpeg', ['-y', '-i', tmpWav, '-codec:a', 'libmp3lame', '-qscale:a', '4', outPath], { stdio: 'ignore' });
  fs.unlinkSync(tmpWav);
}

// 讀現有 manifest
let manifest = {};
if (fs.existsSync(MANIFEST)) {
  const src = fs.readFileSync(MANIFEST, 'utf8');
  const m = src.match(/window\.__TTS\s*=\s*(\{[\s\S]*?\});/);
  if (m) manifest = JSON.parse(m[1]);
}

// 收集所有句子
const files = fs.readdirSync(STORIES_DIR).filter(f => f.endsWith('.json')).sort();
const sentences = new Set();
for (const f of files) {
  if (filterLevel && !f.startsWith(filterLevel + '_')) continue;
  const data = JSON.parse(fs.readFileSync(path.join(STORIES_DIR, f), 'utf8'));
  if (!data.pass) { console.log(`⏭  ${f} not pass,跳過`); continue; }
  for (const s of data.story?.sentences || []) sentences.add(s.j);
}

console.log(`📝 收集 ${sentences.size} 句 from ${files.length} 篇故事`);

// 確認 VOICEVOX 在線
try {
  const v = await fetch(`${ENGINE}/version`).then(r => r.text());
  console.log(`🎤 VOICEVOX ${v.replace(/"/g, '')} 在線`);
} catch {
  console.error('❌ VOICEVOX 沒開!打開 VOICEVOX app 然後重跑'); process.exit(1);
}

let made = 0, skipped = 0;
for (const text of sentences) {
  const h = hashText(text);
  const out = path.join(OUT_DIR, h + '.mp3');
  if (!fs.existsSync(out)) {
    process.stdout.write(`  生 ${h} "${text.slice(0, 25)}..." `);
    const q = await audioQuery(text);
    q.speedScale = 1.0;
    const wav = await synthesis(q);
    wavToMp3(wav, out);
    console.log('✓');
    made++;
  } else {
    skipped++;
  }
  manifest[text] = h;
}

const out = `// Generated by scripts/tts/generate.mjs — do not edit by hand.\nwindow.__TTS = ${JSON.stringify(manifest)};\n`;
fs.writeFileSync(MANIFEST, out, 'utf8');
console.log(`\n📊 made=${made} skipped=${skipped} manifest=${Object.keys(manifest).length}`);
